"""initial_schema

Revision ID: e21296ea2b2c
Revises: 
Create Date: 2026-05-10 22:57:39.961633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e21296ea2b2c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rapid_fire_questions',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('options', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('time_limit_ms', sa.Integer(), server_default=sa.text('15000'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_sessions',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("game_id IN ('wiki', 'picture', 'rapid_fire', 'four_pics', 'crossword')", name='ck_game_sessions_game_id'),
    sa.CheckConstraint("status IN ('active', 'completed', 'abandoned')", name='ck_game_sessions_status'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_game_sessions_player_game')
    )
    op.create_table('rapid_fire_answers',
    sa.Column('id', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=False),
    sa.Column('game_session_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('skipped', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_session_id'], ['game_sessions.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['rapid_fire_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rapid_fire_answers_game_session_id', 'rapid_fire_answers', ['game_session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rapid_fire_answers_game_session_id', table_name='rapid_fire_answers')
    op.drop_table('rapid_fire_answers')
    op.drop_table('game_sessions')
    op.drop_table('rapid_fire_questions')
    op.drop_table('players')
    # ### end Alembic commands ###
